In [1]:
import numba
import numpy as np


**Funciones de prueba:**

In [2]:
@numba.njit
def Sphere(arr):
    """
    Esta función recibe como parámetro un vector de n entradas, ingresado como un np.array,
    y devuelve el escalar que resulta de evaluar la función de la esfera en el vector.
    Se usa en el intervalo de búsqueda [-5.12, 5.12] y su óptimo global está en f([0,..,0])=0

    Ejemplo de uso:
        > Sphere(np.array([0, 0]))

        > 0
    """
    suma = 0.0  # Usar un float para la suma
    for x in arr:
        suma += x ** 2
    return suma

intervaloSphere = (-5.12, 5.12)


# Ejemplo de uso (y compilación AOT)
resultado = Sphere(np.array([1.0, 2.0, 3.0]))
print(resultado)


14.0


In [3]:
@numba.njit
def Ackley(arr):
    """
    Esta función recibe como parámetro un vector de n entradas, ingresado como un np.array,
    y devuelve el escalar que resulta de evaluar la función Ackley en el vector.
    Se usa en el intervalo de búsqueda [-30, 30] y su óptimo global está en f([0,..,0])=0.

    Ejemplo de uso:
        > Ackley(np.array([0, 0]))

        > 0
    """
    suma1 = 0.0
    suma2 = 0.0
    n = arr.shape[0]  # Usar el tamaño del array de NumPy
    for x in arr:
        suma1 += x ** 2
        suma2 += np.cos(2 * np.pi * x)
    
    # Calcular el resultado de la función Ackley
    term1 = 20 + np.exp(1) - 20 * np.exp(-0.2 * np.sqrt(suma1 / n))
    term2 = np.exp(suma2 / n)
    return term1 - term2

intervaloAckley = (-30, 30)

# Ejemplo de uso (y compilación AOT)
resultado = Ackley(np.array([0, 0]))
print(resultado)  # Debería imprimir un valor cercano a 0


-4.440892098500626e-16


In [4]:
@numba.njit
def Griewank(arr):
    """
    Esta función recibe como parámetro un vector de n entradas, ingresado como un np.array,
    y devuelve el escalar que resulta de evaluar la función Griewank en el vector.
    Se usa en el intervalo de búsqueda [-600, 600] y su óptimo global está en f([0,..,0])=0.

    Ejemplo de uso:
        > Griewank(np.array([0, 0]))

        > 0
    """
    suma = 0.0
    m = 1.0  # Inicializar en 1 para la multiplicación de cosenos
    n = arr.shape[0]  # Obtener el número de elementos en el array

    for i in range(1, n + 1):
        x_i = arr[i - 1]  # Acceder al elemento en el índice correspondiente
        suma += (x_i ** 2) / 4000.0  # Sumar la parte de la función
        m *= np.cos(x_i / np.sqrt(i))  # Multiplicar por el coseno

    return 1 + suma - m

intervaloGriewank = (-600, 600)

# Ejemplo de uso (y compilación AOT)
resultado = Griewank(np.array([0, 0]))
print(resultado)  # Debería imprimir 0.0


0.0


In [5]:
@numba.njit
def Rastrigin(arr):
    """
    Esta función recibe como parámetro un vector de n entradas, ingresado como un np.array,
    y devuelve el escalar que resulta de evaluar la función de Rastrigin en el vector.
    Tiene mínimo global en f([0,..,0]).

    Ejemplo de uso:
        > Rastrigin(np.array([2, 3, 6, 7]))

        > 98.0
    """
    n = arr.shape[0]  # Obtener el número de elementos en el array
    suma = 0.0

    for x in arr:
        suma += x ** 2 - 10 * np.cos(2 * np.pi * x)  # Calcular la suma de la función Rastrigin

    return 10 * n + suma  # Retornar el resultado final

intervaloRastrigin = (-5.12, 5.12)

# Ejemplo de uso (y compilación AOT)
resultado = Rastrigin(np.array([2, 3, 6, 7]))
print(resultado)  # Debería imprimir 98.0


98.0


In [6]:
@numba.njit
def Rosenbrock(x):
    """
    Esta función recibe como parámetro un vector de n entradas, ingresado como un array de NumPy
    y devuelve el escalar que resulta de evaluar la función de Rosenbrock en el vector.
    Tiene un mínimo global en f(1, ..., 1).

    Ejemplo de uso:
      > Rosenbrock(np.array([1, 1]))
      > 0
    """
    n = x.shape[0]  # Obtener el tamaño del array
    suma = 0.0
    for i in range(n - 1):
        suma += 100 * (x[i + 1] - (x[i]) ** 2) ** 2 + (x[i] - 1) ** 2
    return suma

intervaloRosenbrock = (-2.048, 2.048)

# Ejemplo de uso (y compilación AOT)
resultado = Rosenbrock(np.array([1, 1]))
print(resultado)  # Debería imprimir 0.0


0.0


**Funciones del algoritmo genético.**

In [7]:
kindividuos = 35 
dimension = 10
intervalo = intervaloRosenbrock
funcion = Rosenbrock
nBits = 20
nCortes = 15
probaMutacion = 0.5
iteraciones = 1000


In [8]:
'''Función que nos genera una población inicial de 2k individuos y 
   recibe como parámetros: La 'k' y el hipercubo al que pertenecen 
   los vectores (o sea, la dimensión 'n' y el intervalo [a,b] al que
   pertenecen cada una de las entradas de los vectores).'''

import numpy as np

@numba.njit
def Generar_Poblacion(k, n, intervalo):
    
   a, b = intervalo

   # Se genera una matriz de tamaño (2k, n) con valores aleatorios
   # uniformes (o sea, una población inicial de 2k individuos donde 
   # cada uno vive en Rn):
   poblacionMatriz = np.random.uniform(a,b, size=(2*k, n))

   return poblacionMatriz # No hacemos la conversión en lista de listas
                          # porque necesitamos de `numba`.


In [9]:
# Ejemplo de uso (y compilación AOT)

pob = Generar_Poblacion(kindividuos, dimension, intervalo)
print(pob[0])


[-1.31169262 -1.66723295  1.16293506 -1.95955548 -0.51100044 -0.92188836
  1.82962758 -0.30824752  1.40099047 -1.43155899]


In [59]:
'''Definimos una función de aptitud que recibe como parámetros una
   función de prueba y una población de 2k individuos y retorna una
   lista con las probabilidades de selección (p_i) de todos los 
   individuos de la población, el mejor individuo en la población,
   la mejor evaluación de éste y el promedio de las evaluaciones.'''


# `aptitud` es un parámetro opcional sólo para elegir qué retorna la 
# función.
@numba.njit
def Probabilidades_De_Seleccion_Y_Mas_Apto(funcion, poblacion, aptitud=1):
    
    # Necesitamos el número de individuos de la población:
    numIndividuos = len(poblacion) 
    
    # Generamos un array con las evaluaciones en la función objetivo
    evaluaciones = np.empty(numIndividuos) # Primero generamos un array
                                           # vacío de tamaño adecuado.
    for i in range(numIndividuos):
        evaluaciones[i] = funcion(poblacion[i])

    # Generamos un array de las aptitudes de los individuos en la 
    # población.
    aptitudes = np.exp(1e-9 * (-evaluaciones))

    # Encontramos el índice del mejor individuo (menor evaluación)
    mejorIndice = np.argmax(aptitudes)
    masApto = poblacion[mejorIndice]

    # Obtenemos el 'tamaño del pastel':
    sumaAptitudes = np.sum(aptitudes)

    # Calculamos las probabilidades de selección (p_i) para todos los
    # individuos:
    probabilidades = aptitudes / sumaAptitudes

    # Inicializamos mejorEval y promedioEva
    mejorEval = np.nan
    promedioEval = np.nan

    # Si aptitud es distinto de 0, calculamos mejor aptitud y promedio de aptitudes
    if aptitud != 0:
        mejorEval = evaluaciones[mejorIndice]
        promedioEval = np.mean(evaluaciones)

    return probabilidades, masApto, mejorEval, promedioEval



In [58]:
# Ejemplo de uso (y compilación AOT)
probas, masApto, mejorEval, promedioEval = Probabilidades_De_Seleccion_Y_Mas_Apto(funcion, pob)

print(probas[0], masApto[0], mejorEval, promedioEval)


0.014285681601812407 0.5611870704154791 481.62559837796437 5036.026594670596


In [12]:
'''Definimos una función que recibe la lista de probabilidades 
   de selección y nos retorna la que corresponde a la de las 
   probabilidades acumulativas.'''

@numba.njit
def Probas_Acumulativas(probabilidades):

    # Calculamos las probabilidades acumulativas (q_i) para todos los
    # individuos:
    probasAcumulativas = np.cumsum(probabilidades)

    return probasAcumulativas # Retornamos las `probasAcumulativas` como
                              # un arreglo de NumPy (igual es iterable).


In [13]:
# Ejemplo de uso (y compilación AOT)
qis = Probas_Acumulativas(probas)
print(qis[16])


0.24285690595056544


Padres mediante el uso de la ruleta:

In [14]:
'''Estas funciones son las que nos ayudan a generar a los padres mediante
   el uso de la ruleta.'''
   

'''La primera es para seleccionar padres (uno) y recibe como parámetro 
   la lista de las probabilidades acumulativas.
   
   Nos retornará el índice en la lista que le corresponde al padre 
   elegido con esa regla.'''

@numba.njit
def Seleccionar_Padre_Ruleta(probasAcumuladas):
   r = np.random.random() # Generamos un número aleatorio entre 0 y 1

   tol=1e-9
   
   # Recorremos las probabilidades acumuladas para seleccionar el padre
   for i in range(len(probasAcumuladas)):
      if r <= probasAcumuladas[i] or np.isclose(r, probasAcumuladas[i], atol=tol):
         return i  # Índice del individuo seleccionado
               
   return -1  # En caso de que no se seleccione, aunque esto no debería suceder.


In [15]:
'''La segunda es para generar la lista de padres elegidos para 
   reproducirse. Necesitamos 2k nuevos individuos, así que se van a 
   elegir k parejas (cada par de padres produce dos hijos).
   La función recibe como parámetros: la lista de individuos, las
   probabilidades acumulativas y un máximo de intentos para intentar evitar
   la generación de clones (en este caso, vamos a considerar un máximo
   de 100 para cada elección de un segundo padre, pero tenemos la 
   apertura de modificarlo después).
   Retorna la lista de parejas de padres elegidos.'''

@numba.njit
def Generar_Parejas(individuos, probasAcumuladas, maxIntentos=100):
    
    numIndividuos = len(individuos)

    # Validación: si no hay suficientes individuos
    if numIndividuos < 2:
        print("Error: No hay suficientes individuos para generar parejas.")
        return np.empty((0, 2, individuos.shape[1]))
        # Regresamos un array vacío

    # Como len(individuos) = 2k, le pedimos que elija len(individuos)/2 
    # parejas de padres.
    parejasNecesarias = numIndividuos // 2
    
    
    parejas_idxs = np.empty((parejasNecesarias, 2), dtype=np.int32)
    # Creamos un array para los índices de tamaño adecuado.
    # Como queremos parejas, el array tiene dos columnas, la idea es que
    # cada fila del array represente una pareja de padres.

    '''En otras palabras, `parejas_idxs` tendrá la forma:
       [[padre1_idx1, padre2_idx1],
       [padre1_idx2, padre2_idx2],
       [padre1_idx3, padre2_idx3],
       ...
       [padre1_idxN, padre2_idxN]]'''


    for i in range(parejasNecesarias):
        padre1_idx = Seleccionar_Padre_Ruleta(probasAcumuladas)

        intentos = 0
        while True:
            padre2_idx = Seleccionar_Padre_Ruleta(probasAcumuladas)
            if padre1_idx != padre2_idx:
                break  # Padres diferentes, salimos del ciclo
            intentos += 1 # No encontramos un padre distinto, hacemos 
                          # otro intento.
            if intentos >= maxIntentos: # Rebasamos los intentos que
                                        # teníamos permitidos.
                padre2_idx = padre1_idx # Aceptamos el clon.
                break

        parejas_idxs[i, 0] = padre1_idx # Primer padre se asigna en la
                                        # fila `i` de la primer columna.
        parejas_idxs[i, 1] = padre2_idx # Segundo padre se asigna en la
                                        # fila `i` de la segunda columna.

    # Ahora construimos el array de parejas usando los índices generados
    # para almacenar las parejas de individuos.
    parejas = np.empty((parejasNecesarias, 2, individuos.shape[1]), dtype=individuos.dtype)
    
    for i in range(parejasNecesarias):
        parejas[i, 0] = individuos[parejas_idxs[i, 0]]  # Primer padre
        parejas[i, 1] = individuos[parejas_idxs[i, 1]]  # Segundo padre

    
    return parejas


In [16]:
# Ejemplo de uso (y compilación AOT)
padres = Generar_Parejas(pob, qis)
print(padres[0])


[[-1.70269744  1.62553339 -0.29238284 -2.00914371 -0.62767471  0.9917213
  -0.70749432  0.0342532  -0.44885612 -0.62821507]
 [-0.52714669 -1.71295834 -1.39203026  0.50663541  1.85597579 -0.42344764
   1.8962166   1.76422425  1.79708204 -0.71557003]]


Funciones auxiliares para la codificación en binario:

In [17]:
@numba.njit
def codifica_real(x, n_bit, intervalo):
    """
    Codifica un número real en el intervalo [a,b] utilizando n_bit bits
    y una partición uniforme en [a, b].

    Parámetros:
    x: número real a codificar.
    n_bit: número de bits a utilizar.
    intervalo: (a, b), extremos del intervalo.

    Retorno:
    Arreglo binario que representa al número real x con n_bit bits
    en el intervalo [a, b].
    """
    a, b = intervalo

    # Calcula la precisión de la representación.
    precision = (b - a) / ((2 ** n_bit) - 1)

    # Asegura que el número esté dentro del rango de la partición.
    x = max(a, min(b, x))

    # Calcula el índice del número en la partición.
    index = int((x - a) / precision)

    # Codifica el índice a binario
    if index < 0 or index >= (1 << n_bit):
        raise ValueError(f"Índice fuera del rango representable con {n_bit} bits.")

    x_binario = np.zeros(n_bit, dtype=np.int32)
    for i in range(n_bit - 1, -1, -1):
        x_binario[i] = index & 1
        index >>= 1

    return x_binario

@numba.njit
def codifica_vector(vector_reales, n_bit, intervalo):
    """
    Codifica un vector de números reales en un vector de vectores binarios
    utilizando n_bit bits.

    Parámetros:
    vector_reales: Arreglo de números reales a codificar
    n_bit: Número de bits a utilizar para las entradas de nuestro arreglo.
    intervalo: (a, b), extremos del intervalo.

    Retorno:
    Arreglo de arreglos binarios, donde cada sub-arreglo representa un número real
    codificado en binario.
    """
    dim_x = vector_reales.shape[0]

    # Inicializa un arreglo vacío para almacenar los vectores binarios.
    vector_binario = np.empty((dim_x, n_bit), dtype=np.int32)

    for i in range(dim_x):
        vector_binario[i] = codifica_real(vector_reales[i], n_bit, intervalo)

    return vector_binario


In [18]:
'''Función que reciba la lista de parejas de padres seleccionadas
   para la reproducción, el número de `nBits` para la codificación
   en binario y el intervalo donde se encuentran las entradas de 
   los vectores.
   Retorna las parejas de padres seleccionadas para la reproducción
   como parejas de arreglos de bits.'''

@numba.njit
def Padres_Binarios(parejas, nBits, intervalo):
    """
    Codifica parejas de vectores en binario.
    """
    numParejas = parejas.shape[0]
    parejasBinarias = np.empty((numParejas, 2, parejas.shape[2], nBits), dtype=np.int32)

    for i in range(numParejas):
        padre1 = parejas[i, 0]  # Vector 1
        padre2 = parejas[i, 1]  # Vector 2

        # Codifica cada padre en binario y lo almacena.
        parejasBinarias[i, 0] = codifica_vector(padre1, nBits, intervalo)
        parejasBinarias[i, 1] = codifica_vector(padre2, nBits, intervalo)

    return parejasBinarias


In [19]:
# Ejemplo de uso (y compilación AOT)
padresBinarios = Padres_Binarios(padres, nBits, intervalo)
print(padresBinarios[0,0])


[[0 0 0 1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 1]
 [1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 0 0 1 1 1]
 [0 1 1 0 1 1 0 1 1 0 1 1 1 0 0 1 1 1 0 1]
 [0 0 0 0 0 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1]
 [0 1 0 1 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0]
 [1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1]
 [0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0]]


In [20]:
'''Función que realiza la cruza de n puntos. Recibe como parámetros: el
   array de los padres (en arreglos binarios), el número de cortes que 
   se quieren hacer por cromosoma.Retorna una lista de 2k hijos (como 
   arreglos binarios).'''

@numba.njit
def Cruza_N_Puntos_np_numba(padres, nPuntos):
    numParejas = padres.shape[0]  # Número de parejas de padres
    numCromosomas = padres[0, 0].shape[0]  # Número de cromosomas por padre (filas)
    numGenes = padres[0, 0].shape[1]  # Número de genes por cromosoma (columnas)

    # Inicializamos un array vacío para almacenar los hijos
    hijos = np.empty((2 * numParejas, numCromosomas, numGenes), dtype=np.int32)

    # Iteramos sobre cada pareja de padres
    for pareja_idx in range(numParejas):
        padre1 = padres[pareja_idx, 0]
        padre2 = padres[pareja_idx, 1]

        # Generamos los arrays vacíos para los hijos de la pareja actual
        hijo1 = np.empty_like(padre1)
        hijo2 = np.empty_like(padre2)

        # Generar n puntos de corte únicos
        puntosCorte = np.random.choice(np.arange(1, numGenes), nPuntos, replace=False)
                      # `replace=False` es para garantizar que los puntos de corte sí
                      # sean diferentes.
        puntosCorte.sort()  # Asegura que los puntos de corte están ordenados.

        # Iteramos sobre cada cromosoma de los padres
        for cromo_idx in range(numCromosomas):
            cromo1 = padre1[cromo_idx]
            cromo2 = padre2[cromo_idx]

            # Alternamos segmentos entre los padres
            ultimo_punto = 0
            switch = False

            for punto in np.append(puntosCorte, numGenes):  # Añadimos el último punto
                if switch:
                    hijo1[cromo_idx, ultimo_punto:punto] = cromo2[ultimo_punto:punto]
                    hijo2[cromo_idx, ultimo_punto:punto] = cromo1[ultimo_punto:punto]
                else:
                    hijo1[cromo_idx, ultimo_punto:punto] = cromo1[ultimo_punto:punto]
                    hijo2[cromo_idx, ultimo_punto:punto] = cromo2[ultimo_punto:punto]

                switch = not switch
                ultimo_punto = punto

        # Guardamos los hijos generados en el array de hijos
        hijos[2 * pareja_idx] = hijo1
        hijos[2 * pareja_idx + 1] = hijo2

    return hijos


In [21]:
# Ejemplo de uso (y compilación AOT)
hijosBinarios = Cruza_N_Puntos_np_numba(padresBinarios, nCortes)
print(hijosBinarios[0])


[[0 1 0 1 1 1 0 1 1 0 0 1 1 1 0 1 1 0 0 0]
 [1 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0]
 [0 0 1 0 1 1 0 0 1 0 1 1 1 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0]
 [0 1 0 1 0 0 0 1 1 1 1 0 1 1 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1]
 [0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0]
 [1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 0]
 [0 1 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 1 0 1]]


In [22]:
'''Operador de mutación de un bit: Recibe como parámetros
   la lista de los hijos como arreglos de bits y una 
   probabilidad de mutación.
   Itera por cada hijo y por cada cromosoma, en este último
   genera un número aleatorio para determinar si habrá una
   mutación en dicho cromosoma; de ser así, se elige un bit 
   al azar y se cambia su valor.
   Se retorna la lista de los hijos (posiblemente) mutados.'''

@numba.njit
def Mutador_1_flip_np_numba(hijosBinarios, probaMutacion):
    
    # Obtenemos el número de individuos y cromosomas
    numHijos = hijosBinarios.shape[0]
    numCromosomas = hijosBinarios.shape[1]
    
    numBits = hijosBinarios.shape[2]

    hijosMutados = np.copy(hijosBinarios)
    
    # Recorremos cada individuo
    for i in range(numHijos):
        # Recorremos cada cromosoma del individuo
        for j in range(numCromosomas):
            # Generamos un número aleatorio
            if np.random.rand() < probaMutacion:
                # Elegimos un bit al azar dentro del cromosoma
                bit_a_flip = np.random.randint(0, numBits)
                # Mutar el bit
                hijosMutados[i, j, bit_a_flip] ^= 1  # Flip bit
                # Modificamos directamente sobre hijosBinarios porque
                # a los que realmente consideraremos como hijos en cada
                # generación es a los generados después de la reproducción
                # y mutación.

    return hijosMutados


In [23]:
# Ejemplo de uso (y compilación AOT)
hijosMutados = Mutador_1_flip_np_numba(hijosBinarios, probaMutacion)
print(hijosMutados[0])


[[0 1 0 1 1 1 0 1 1 0 0 1 1 1 0 1 1 0 0 0]
 [0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0]
 [0 0 1 0 1 1 0 0 1 0 1 1 1 0 0 1 1 0 1 0]
 [0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0]
 [0 1 0 1 0 0 0 0 1 1 1 0 1 1 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1]
 [0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0]
 [1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 1 1 1 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0]
 [0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1]]


In [24]:
@numba.njit
def Hijos_Decodificados(hijosMutados, nBits, intervalo):
    """
    Decodifica un array de hijos mutados en números reales.

    Parámetros:
    hijosMutados: np.array de hijos mutados, donde cada hijo es un vector de bits
    nBits: número de bits a utilizar para cada número
    intervalo: de la forma [a, b]

    Retorno:
    np.array de números reales decodificados
    """
    
    num_hijos = hijosMutados.shape[0]      # Obtenemos el número de hijos
    num_cromosomas = hijosMutados.shape[1]  # Obtenemos el número de cromosomas
    
    # Crea un array vacío para los hijos decodificados
    hijosDecodificados = np.empty((num_hijos, num_cromosomas))  # De la forma correcta

    for i in range(num_hijos):
        for j in range(num_cromosomas):
            hijoMutado = hijosMutados[i, j]  # Acceder al cromosoma
            
            # Decodificación directa del cromosoma
            a, b = intervalo
            precision = (b - a) / ((2 ** nBits) - 1)  # Calcula la precisión de la representación
            # Convierte el vector de bits en un número entero
            indice = 0
            for bit in range(nBits):
                indice += hijoMutado[bit] * (2 ** (nBits - 1 - bit))  # Cálculo del valor decimal
            hijoDecodificado = a + indice * precision  # Calcula el número real decodificado
            
            # Almacena el resultado en el array de salida
            hijosDecodificados[i, j] = hijoDecodificado

    return hijosDecodificados


In [25]:
# Ejemplo de uso (y compilación AOT)
hijosDecodificados = Hijos_Decodificados(hijosMutados, nBits, intervalo)
print(hijosDecodificados[0])


[-0.55015482 -1.20499138 -1.33239776 -1.60921052 -0.75317845  1.62990585
 -1.74792159  1.18431558 -0.20879512 -0.74294797]


Funciones que realizan el reemplazo generacional:

In [26]:
'''Función que realiza el reemplazo con elitismo.'''

@numba.njit
def Reemplazo_Elitismo(hijosDecodificados, masApto):

    numHijos, dimension = hijosDecodificados.shape

    # Elegimos el índice de un hijo al azar para eliminarlo:
    idx_aleatorio = np.random.randint(0, numHijos)

    # Creamos un nuevo array sin el hijo borrado:
    hijosReducidos = np.empty((numHijos-1, dimension))
    contador = 0
    for i in range(numHijos):
        if i != idx_aleatorio:
            hijosReducidos[contador, :] = hijosDecodificados[i, :]
            contador += 1

    # Creamos un nuevo array con el más apto antes de la reproducción:
    siguienteGeneracion = np.empty((numHijos, dimension))
    for i in range(numHijos-1):
        siguienteGeneracion[i, :] = hijosReducidos[i, :]
    siguienteGeneracion[numHijos-1, :] = masApto

    return siguienteGeneracion


In [27]:
# Ejemplo de uso (y compilación AOT)
siguienteGen = Reemplazo_Elitismo(hijosDecodificados, masApto)
print(siguienteGen[-1])


[ 0.56118707  0.46643256 -0.44438647  0.91629775 -0.04867712 -0.88652229
  0.36203675 -0.34246496  0.67911174  1.66297597]


In [28]:
'''Función que realiza el reemplazo generacional completo.'''

@numba.njit
def Reemplazo_Generacional(hijosDecodificados):
    
    # Hacemos el reemplazo generacional completo:
    siguienteGen = np.copy(hijosDecodificados)

    return siguienteGen
    

In [29]:
# Ejemplo de uso (y compilación AOT)
siguienteGen = Reemplazo_Generacional(hijosDecodificados)
print(siguienteGen[-1])


[-8.18162890e-01  5.82822821e-01  1.48451313e-01 -3.13971003e-01
 -9.94141573e-04 -8.61209806e-01  9.49551687e-02 -7.98502715e-01
  3.56666356e-01 -1.61300349e+00]


In [30]:
'''Función que realiza el reemplazo de los peores.
   Como parámetro tenemos la fracción de la (función
   piso) población que queremos reemplazar.'''

@numba.njit
def Reemplazo_Peores(hijosDecodificados, poblacion, funcion, 
                     fraccionReemplazo):

    # Verificamos que la fracción de reemplazo esté entre 0 y 1
    assert 0 < fraccionReemplazo <= 1, "La fracción de reemplazo debe estar entre 0 y 1"
    
    # Número de individuos a reemplazar (fracción de los peores)
    numReemplazos = int(fraccionReemplazo * len(poblacion))

    # Calculamos las evaluaciones de todos los individuos en 
    # la `poblacion` (la actual, donde están los padres)
    evaluaciones = np.empty(len(poblacion)) # Array vacío
    for i in range(len(poblacion)):
        evaluaciones[i] = funcion(poblacion[i])

    # Calculamos las aptitudes de los individuos:
    aptitudes = np.exp(1e-9 * (-evaluaciones))

    # Ordenamos los individuos de acuerdo a su aptitud en orden 
    # ascendente para que los peores estén primero.
    indicesOrdenados = np.argsort(aptitudes) 

    # Seleccionamos los índices de los peores `num_reemplazos` individuos
    indicesPeores = indicesOrdenados[:numReemplazos] 
   
    # Creamos una copia de la población para hacer el reemplazo de 
    # los peores.
    nuevaPoblacion = np.copy(poblacion)

    # Reemplazamos los peores individuos con los nuevos hijos
    nuevaPoblacion[indicesPeores] = hijosDecodificados[:numReemplazos]
    # En este paso hay un cierto componente estocástico al hacer 
    # el reemplazo de los peores individuos con los nuevos hijos de
    # este modo porque los hijos en `hijosDecodificados` no están 
    # ordenados en función de su aptitud.
    # Esto es intencional para tratar de evitar convergencia 
    # prematura.

    return nuevaPoblacion


In [31]:
# Ejemplo de uso (y compilación AOT)
fraccionReemplazo = 0.5 # La mitad
siguienteGen = Reemplazo_Peores(hijosDecodificados, pob, funcion, fraccionReemplazo)
print(siguienteGen[-1])


[-0.14201771  1.17454995 -1.53284326  0.5126665  -1.07278423 -1.83083182
  1.21429999 -1.34682746 -1.03650294  0.52279933]


Algoritmos genéticos:

In [74]:
@numba.njit
def AG_Reemplazo_Elitismo(funcion, intervalo, dimension, 
                          kindividuos, nBits, nCortes, 
                          probaMutacion, iteraciones):

    # Generamos a nuestra población inicial:
    poblacion = Generar_Poblacion(kindividuos, dimension, intervalo)

    # Inicializamos para almacenar mejor y promedio en cada iteración
    mejores_por_iteracion = np.zeros(iteraciones)
    promedios_por_iteracion = np.zeros(iteraciones)

    # Repetimos esto mientras tengamos iteraciones:
    for i in range(iteraciones):

        # Calculamos las probabilidades de selección y obtenemos el individuo más apto
        probas_pi, masApto, mejorEval, promedioEval = Probabilidades_De_Seleccion_Y_Mas_Apto(funcion, poblacion)

        # Guardamos los resultados de esta iteración
        mejores_por_iteracion[i] = mejorEval
        promedios_por_iteracion[i] = promedioEval

        # Calculamos las probabilidades acumulativas
        probasAcumulativas_qi = Probas_Acumulativas(probas_pi)

        # Seleccionamos a los padres:
        padres = Generar_Parejas(poblacion, probasAcumulativas_qi)

        # Convertimos a los padres en arreglos de bits.
        padresBinarios = Padres_Binarios(padres, nBits, intervalo)

        # Cruzamos a los padres para generar hijos (como arreglos binarios).
        hijosBinarios = Cruza_N_Puntos_np_numba(padresBinarios, nCortes)

        # Aplicamos la mutación 1-flip a los hijos.
        hijosMutados = Mutador_1_flip_np_numba(hijosBinarios, probaMutacion)

        # Decodificamos a los hijos a su representación original como vectores de reales.
        hijosDecodificados = Hijos_Decodificados(hijosMutados, nBits, intervalo)

        # Incluimos el individuo más apto de la generación anterior en la nueva población
        poblacion = Reemplazo_Elitismo(hijosDecodificados, masApto)

    
    return mejores_por_iteracion, promedios_por_iteracion


In [75]:
# Ejemplo de uso (compilación AOT)
mejorEval, promedioEval = AG_Reemplazo_Elitismo(funcion, intervalo, dimension, 
                                                kindividuos, nBits, nCortes, 
                                                probaMutacion, iteraciones)

print(mejorEval)
print(promedioEval)


[1128.37268296  900.03837269  881.55494653  429.37939581  429.37939581
  429.37939581  429.37939581  429.37939581  429.37939581  429.37939581
  429.37939581  429.37939581  276.12564069  276.12564069  276.12564069
  276.12564069  276.12564069  276.12564069  276.12564069  260.72300847
  260.72300847  260.72300847  260.72300847  260.72300847  260.72300847
  260.72300847  260.72300847  260.72300847  260.72300847  260.72300847
  260.72300847  260.72300847  260.72300847  260.72300847  260.72300847
  260.72300847  260.72300847  260.72300847  260.72300847  260.72300847
  260.72300847  260.72300847  260.72300847  260.72300847  260.72300847
  260.72300847  260.72300847  260.72300847  260.72300847  260.72300847
  260.72300847  260.72300847  219.14867684  219.14867684  219.14867684
  219.14867684  219.14867684  219.14867684  219.14867684  219.14867684
  219.14867684  219.14867684  219.14867684  219.14867684  219.14867684
  219.14867684  219.14867684  219.14867684  219.14867684  219.14867684
  219.

In [76]:
@numba.njit
def AG_Reemplazo_Generacional(funcion, intervalo, dimension, 
                              kindividuos, nBits, nCortes, 
                              probaMutacion, iteraciones):

    # Generamos a nuestra población inicial:
    poblacion = Generar_Poblacion(kindividuos, dimension, intervalo)

    # Inicializamos para almacenar mejor y promedio en cada iteración
    mejores_por_iteracion = np.zeros(iteraciones)
    promedios_por_iteracion = np.zeros(iteraciones)

    # Repetiremos esto mientras tengamos iteraciones:
    for i in range(iteraciones):

        # Calculamos las probabilidades de selección y obtenemos el individuo más apto
        probas_pi, masApto, mejorEval, promedioEval = Probabilidades_De_Seleccion_Y_Mas_Apto(funcion, poblacion)

        # Guardamos los resultados de esta iteración
        mejores_por_iteracion[i] = mejorEval
        promedios_por_iteracion[i] = promedioEval
        
        # Calculamos las probabilidades acumulativas
        probasAcumulativas_qi = Probas_Acumulativas(probas_pi)

        # Seleccionamos a los padres:
        padres = Generar_Parejas(poblacion, probasAcumulativas_qi)

        # Convertimos a los padres en arreglos de bits.
        padresBinarios = Padres_Binarios(padres, nBits, intervalo)

        # Cruzamos a los padres para generar hijos (como arreglos binarios).
        hijosBinarios = Cruza_N_Puntos_np_numba(padresBinarios, nCortes)

        # Aplicamos la mutación 1-flip a los hijos.
        hijosMutados = Mutador_1_flip_np_numba(hijosBinarios, probaMutacion)

        # Decodificamos a los hijos a su representación original como vectores de reales.
        hijosDecodificados = Hijos_Decodificados(hijosMutados, nBits, intervalo)
        
        # Generamos la siguiente generación, con reemplazo generacional completo.
        poblacion = Reemplazo_Generacional(hijosDecodificados)

    return mejores_por_iteracion, promedios_por_iteracion


In [77]:
# Ejemplo de uso (y compilación AOT)
mejorEval, promedioEval = AG_Reemplazo_Generacional(funcion, intervalo, dimension, 
                                                    kindividuos, nBits, nCortes, 
                                                    probaMutacion, iteraciones)

print(mejorEval)
print(promedioEval)


[ 959.99725269 1197.62407576 1153.43229729  529.27681652  977.30192329
  612.16772531  550.94516862  995.23648851  771.29999637  797.16479221
  937.49328452  981.51313865 1248.94815371 1009.74864499  512.84028241
 1189.99152748 1406.46570632 1178.85589425  687.72546153 1352.3941646
  832.91433967  528.7150745   232.98652224  451.79929397  799.35861757
  457.89853097  889.13276748 1266.3240015   685.92694056 1179.72625599
 1585.28077367 1230.83129652 1154.94847329  290.59972859  382.06803406
  892.92648568  811.54544486 1851.24747737 1171.55216667  937.24105121
  727.29363585  679.24962525  663.60577343  987.55151363  758.45233466
  505.04876323  998.24099677  359.92271674  330.05331309  318.69009676
  432.02926015 1449.44642842  296.6303053   351.00114369  335.55989336
  793.63934006  980.00340481  589.91646115  685.80787341  485.66067387
  961.20380606  690.12297439 1112.53579857  973.91310099  270.56286594
  953.01531865  961.66675551  992.31668808  747.04597111 1289.77551186
  620.1

In [78]:
@numba.njit
def AG_Reemplazo_Peores(funcion, intervalo, dimension, 
                        kindividuos, nBits, nCortes, 
                        probaMutacion, iteraciones,
                        fraccionReemplazo):

    # Generamos a nuestra población inicial:
    poblacion = Generar_Poblacion(kindividuos, dimension, intervalo)

    # Inicializamos para almacenar mejor y promedio en cada iteración
    mejores_por_iteracion = np.zeros(iteraciones)
    promedios_por_iteracion = np.zeros(iteraciones)

    # Repetiremos esto mientras tengamos iteraciones:
    for i in range(iteraciones):

        # Calculamos las probabilidades de selección y obtenemos el individuo más apto
        probas_pi, masApto, mejorEval, promedioEval = Probabilidades_De_Seleccion_Y_Mas_Apto(funcion, poblacion)

        # Guardamos los resultados de esta iteración
        mejores_por_iteracion[i] = mejorEval
        promedios_por_iteracion[i] = promedioEval

        # Calculamos las probabilidades acumulativas
        probasAcumulativas_qi = Probas_Acumulativas(probas_pi)

        # Seleccionamos a los padres:
        padres = Generar_Parejas(poblacion, probasAcumulativas_qi)

        # Convertimos a los padres en arreglos de bits.
        padresBinarios = Padres_Binarios(padres, nBits, intervalo)

        # Cruzamos a los padres para generar hijos (como arreglos binarios).
        hijosBinarios = Cruza_N_Puntos_np_numba(padresBinarios, nCortes)

        # Aplicamos la mutación 1-flip a los hijos.
        hijosMutados = Mutador_1_flip_np_numba(hijosBinarios, probaMutacion)

        # Decodificamos a los hijos a su representación original como vectores de reales.
        hijosDecodificados = Hijos_Decodificados(hijosMutados, nBits, intervalo)
        
        # Generamos la siguiente generación, incluyendo el individuo más apto.
        poblacion = Reemplazo_Peores(hijosDecodificados, poblacion, funcion, fraccionReemplazo)

    return mejores_por_iteracion, promedios_por_iteracion


In [80]:
# Ejemplo de uso (y compilación AOT)
mejorEval, promedioEval = AG_Reemplazo_Peores(funcion, intervalo, dimension, 
                                              kindividuos, nBits, nCortes, 
                                              probaMutacion, iteraciones,
                                              fraccionReemplazo)

print(mejorEval)
print(promedioEval)


[433.90657536 433.90657536 405.09296642 405.09296642 405.09296642
 405.09296642 405.09296642 405.09296642 405.09296642 379.214896
 379.214896   379.214896   379.214896   379.214896   379.214896
 379.214896   379.214896   379.214896   379.214896   379.214896
 375.439982   375.439982   375.439982   333.64652749 333.64652749
 219.15476035 219.15476035 219.15476035 219.15476035 219.15476035
 219.15476035 219.15476035 169.95918381 169.95918381 169.95918381
 169.95918381 108.26790161 108.26790161 108.26790161 108.26790161
 108.26790161 108.26790161 108.26790161 108.26790161 108.26790161
 108.26790161 108.26790161 108.26790161  71.3161795   71.3161795
  71.3161795   71.3161795   71.3161795   71.3161795   71.3161795
  71.3161795   71.3161795   71.3161795   71.3161795   71.3161795
  71.3161795   71.3161795   71.3161795   71.3161795   71.3161795
  71.3161795   60.9067022   60.9067022   60.9067022   25.5359663
  25.5359663   25.5359663   25.5359663   25.5359663   25.5359663
  25.5359663   25.5359

Hasta aquí: Por separado, tenemos todo lo necesario para la implementación del algoritmo genético.

**Plantillas para las 30 ejecuciones del Algoritmo Genético:**

Para el de reemplazo con elitismo:

In [131]:
import time
import datetime

# Función principal para ejecutar 30 veces
def ejecutar_algoritmo_y_guardar_resultados(ejecuciones=30, iteraciones=1000):
    funcion = Rosenbrock
    intervalo = intervaloRosenbrock
    dimension = 10
    kindividuos = 35
    nBits = 20
    nCortes = 15
    probaMutar = 0.1

    for j in range(ejecuciones):
        # Generar semilla única para cada ejecución
        seed = int(time.time()) % (2**32)
        seed += j
        np.random.seed(seed)

        # Ejecutamos el algoritmo
        mejores_eval, promedios_eval = AG_Reemplazo_Elitismo(funcion, intervalo, dimension, 
                                                             kindividuos, nBits, nCortes, 
                                                             probaMutar, iteraciones)
        
        # Guardar resultados en un archivo CSV por cada ejecución
        nombre_archivo = f"Rosenbrock_resultados_elitismo_{j+1}_semilla_{seed}.csv"
        
        # Guardar los resultados en el archivo
        header = f"MejorEval,PromedioEval\n# Semilla: {seed}"
        datos = np.column_stack((mejores_eval, promedios_eval))
        header = f"MejorEval,PromedioEval\n# Semilla: {seed}"
        np.savetxt(nombre_archivo, datos, delimiter=',', header=header, comments='', fmt='%f,%f')

# Ejecutar el algoritmo y guardar resultados
ejecutar_algoritmo_y_guardar_resultados()


Para el reemplazo generacional:

In [119]:
import time
import datetime

# Función principal para ejecutar 30 veces
def ejecutar_algoritmo_y_guardar_resultados(ejecuciones=30, iteraciones=1000):
    funcion = Rosenbrock
    intervalo = intervaloRosenbrock
    dimension = 10
    kindividuos = 35
    nBits = 20
    nCortes = 15
    probaMutar = 0.1

    for j in range(ejecuciones):
        # Generar semilla única para cada ejecución
        seed = int(time.time()) % (2**32)
        seed += j
        np.random.seed(seed)

        # Ejecutamos el algoritmo
        mejores_eval, promedios_eval = AG_Reemplazo_Generacional(funcion, intervalo, dimension, 
                                                                 kindividuos, nBits, nCortes, 
                                                                 probaMutar, iteraciones)
        
        # Guardar resultados en un archivo CSV por cada ejecución
        nombre_archivo = f"Rosenbrock_resultados_generacional_{j+1}_semilla_{seed}.csv"
        
        # Guardar los resultados en el archivo
        header = f"MejorEval,PromedioEval\n# Semilla: {seed}"
        datos = np.column_stack((mejores_eval, promedios_eval))
        header = f"MejorEval,PromedioEval\n# Semilla: {seed}"
        np.savetxt(nombre_archivo, datos, delimiter=',', header=header, comments='', fmt='%f,%f')

# Ejecutar el algoritmo y guardar resultados
ejecutar_algoritmo_y_guardar_resultados()


Para el reemplazo de los peores:

In [139]:
import time
import datetime

# Función principal para ejecutar 30 veces
def ejecutar_algoritmo_y_guardar_resultados(ejecuciones=30, iteraciones=1000):
    funcion = Rosenbrock
    intervalo = intervaloRosenbrock
    dimension = 10
    kindividuos = 35
    nBits = 20
    nCortes = 12
    probaMutar = 0.1
    fraccionReemplazo = 0.25

    for j in range(ejecuciones):
        # Generar semilla única para cada ejecución
        seed = int(time.time()) % (2**32)
        seed += j
        np.random.seed(seed)

        # Ejecutamos el algoritmo
        mejores_eval, promedios_eval = AG_Reemplazo_Peores(funcion, intervalo, dimension, 
                                                           kindividuos, nBits, nCortes, 
                                                           probaMutar, iteraciones,
                                                           fraccionReemplazo)
        
        # Guardar resultados en un archivo CSV por cada ejecución
        nombre_archivo = f"Rosenbrock_resultados_peores_{j+1}_semilla_{seed}.csv"
        
        # Guardar los resultados en el archivo
        header = f"MejorEval,PromedioEval\n# Semilla: {seed}"
        datos = np.column_stack((mejores_eval, promedios_eval))
        header = f"MejorEval,PromedioEval\n# Semilla: {seed}"
        np.savetxt(nombre_archivo, datos, delimiter=',', header=header, comments='', fmt='%f,%f')

# Ejecutar el algoritmo y guardar resultados
ejecutar_algoritmo_y_guardar_resultados()


**Función para el cálculo de la entropía:**

In [102]:
'''Recibe como parámetros: la población en arreglos de nBits.
   Retorna: la entropía total de la población.'''

@numba.njit
def Entropia_Total(poblacion):
    
   # Obtenemos el tamaño de la población, cromosomas y bits
   nIndividuos, nCromosomas, nBits = poblacion.shape

   # Inicializamos un array para almacenar las entropías por gen
   entropiasPorGen = np.zeros(nBits)  # Inicializamos la entropía por gen (bit)

   # Calculamos la entropía para cada gen
   for b in range(nBits):
      # Contamos la cantidad de 1s y 0s en la posición b (gen)
      conteo_1s = 0
      for i in range(nIndividuos):
         for j in range(nCromosomas):
            conteo_1s += poblacion[i, j, b]
        
      conteo_0s = nIndividuos * nCromosomas - conteo_1s  # Calculamos la cantidad de 0s

      # Calculamos las probabilidades
      totalBits = nIndividuos * nCromosomas
      p_1 = conteo_1s / totalBits
      p_0 = conteo_0s / totalBits

      # Calculamos la entropía solo si hay probabilidades positivas
      entropia_gen = 0.0
      if p_1 > 0:
         entropia_gen -= p_1 * np.log2(p_1)
      if p_0 > 0:
         entropia_gen -= p_0 * np.log2(p_0)
        
      # Almacenamos la entropía del gen
      entropiasPorGen[b] = entropia_gen

   # Calculamos la entropía total como el promedio de las entropías por gen
   entropia_total = np.sum(entropiasPorGen) / nBits  # Promedio

   return entropia_total


In [118]:
# Ejemplo de uso (y compilación AOT)
poblacion = np.array([
    [[0, 1, 1, 1, 0],
     [1, 1, 1, 1, 0],
     [1, 1, 1, 1, 0],
     [1, 1, 1, 1, 0]],

    [[0, 1, 1, 1, 0],
     [1, 1, 1, 1, 0],
     [1, 1, 1, 1, 0],
     [1, 1, 1, 1, 0]],

    [[1, 1, 1, 1, 0],
     [1, 1, 1, 1, 0],
     [1, 1, 1, 1, 0],
     [1, 1, 1, 1, 0]]
])

entropiaPoblacional = Entropia_Total(poblacion)
print(entropiaPoblacional)


0.13000448432967082
